"""LLM-driven selection or creation of the best-fit extraction schema.

Flow overview:

1. Check the local memory store – if a schema already exists that matches the
   doc domain, use it (unchanged logic).
2. Otherwise run the **variant generation** process, which asks the LLM for
   multiple candidate schemas (maximalist, minimalist, balanced).
3. Let the **Schema-Referee** LLM pick the winner.
4. Persist the winning schema with per-field description & rationale.
"""

from __future__ import annotations

import json
from typing import List

# stdlib
import sys, os

# third-party / internal
from ..interfaces import Document
from ..memory import FileMemoryStore, SchemaRecord
from ..services import schema_variants

# Env flag to toggle merge referee
_USE_MERGE = bool(os.getenv("EDGAR_AI_MERGE_REFEREE"))

# ---------------------------------------------------------------------------
# Public helper
# ---------------------------------------------------------------------------


def choose_schema(doc: Document, memory: FileMemoryStore, *, verbose: bool = False) -> dict:  # noqa: D401
    """Return a schema dict appropriate for *doc*.

    If the local memory store already contains a schema that should apply, we
    still rely on the `schema_variants` referee to pick among them so the same
    selection logic is used consistently.
    """

    existing_records: List[SchemaRecord] = memory.list_schema_records()

    def _log(msg: str) -> None:  # local helper respecting verbose flag
        if verbose:
            print(f"[choose_schema] {msg}", file=sys.stderr)

    # -------------------------------------------------------------------
    # 1. If no existing schema -> generate fresh variants & referee
    # -------------------------------------------------------------------
    if not existing_records:
        _log("No stored schema – generating variants (maximalist/minimalist/balanced)…")
        variants = schema_variants.generate_variants(doc)
        for i, v in enumerate(variants):
            _log(f"Variant {i}: {len(v['fields'])} fields – overview: {v.get('overview','')[:80]}…")

        if _USE_MERGE:
            _log("Running merge referee…")
            winning_schema = schema_variants.merge_referee(variants, doc)
            _log(f"Merge referee produced {len(winning_schema.get('fields', []))} fields")
        else:
            winner_idx, reason = schema_variants.referee(variants, doc)
            _log(f"Referee selected variant {winner_idx} → {reason}")
            winning_schema = variants[winner_idx]

        schema_id = f"schema_{len(existing_records) + 1}"
        memory.save_schema_record(schema_id, winning_schema, rationale="auto-generated by variant flow")
        return winning_schema

    # -------------------------------------------------------------------
    # 2. There are already stored schemas.  Feed them *plus* new variants to
    #    the referee so it can decide whether to keep using one of the former
    #    or switch to a fresh schema.
    # -------------------------------------------------------------------
    stored_schemas = [r.schema_def for r in existing_records]

    # We ask Variant-Generator for *at most* one balanced proposal so the
    # referee has a challenger if the stored ones are stale.
    _log(f"{len(existing_records)} stored schema(s) found – generating one challenger variant…")
    challenger_variants = schema_variants.generate_variants(doc, minimal_only=True)
    _log("Challenger variant created.")

    all_candidates = stored_schemas + challenger_variants

    if _USE_MERGE:
        _log("Running merge referee with stored + challenger schemas…")
        winning_schema = schema_variants.merge_referee(all_candidates, doc)
        reason = "merged schema"
    else:
        winner_idx, reason = schema_variants.referee(all_candidates, doc)
        _log(f"Referee chose schema index {winner_idx} (new: {winner_idx >= len(stored_schemas)}) – {reason}")
        winning_schema = all_candidates[winner_idx]

        # If the winner is brand-new (i.e. came from challenger list) we persist it
        is_new = winner_idx >= len(stored_schemas)
        if is_new:
            schema_id = f"schema_{len(existing_records) + 1}"
            memory.save_schema_record(schema_id, winning_schema, rationale="promoted by referee")

    # When merge path used and schema not yet stored, persist it
    if _USE_MERGE and winning_schema not in [r.schema_def for r in existing_records]:
        schema_id = f"schema_{len(existing_records) + 1}"
        memory.save_schema_record(schema_id, winning_schema, rationale="merged by referee")

    return winning_schema