"""LLM-driven selection or creation of the best-fit extraction schema.

Flow overview:

1. Check the local memory store – if a schema already exists that matches the
   doc domain, use it (unchanged logic).
2. Otherwise run the **variant generation** process, which asks the LLM for
   multiple candidate schemas (maximalist, minimalist, balanced).
3. Let the **Schema-Referee** LLM pick the winner.
4. Persist the winning schema with per-field description & rationale.
"""

from __future__ import annotations

import json
from typing import List

from ..interfaces import Document
from ..memory import FileMemoryStore, SchemaRecord
from ..services import schema_variants

# ---------------------------------------------------------------------------
# Public helper
# ---------------------------------------------------------------------------


def choose_schema(doc: Document, memory: FileMemoryStore) -> dict:  # noqa: D401
    """Return a schema dict appropriate for *doc*.

    If the local memory store already contains a schema that should apply, we
    still rely on the `schema_variants` referee to pick among them so the same
    selection logic is used consistently.
    """

    existing_records: List[SchemaRecord] = memory.list_schema_records()

    # -------------------------------------------------------------------
    # 1. If no existing schema -> generate fresh variants & referee
    # -------------------------------------------------------------------
    if not existing_records:
        variants = schema_variants.generate_variants(doc)
        winner_idx, _reason = schema_variants.referee(variants, doc)
        winning_schema = variants[winner_idx]

        schema_id = f"schema_{len(existing_records) + 1}"
        memory.save_schema_record(schema_id, winning_schema, rationale="auto-generated by variant flow")
        return winning_schema

    # -------------------------------------------------------------------
    # 2. There are already stored schemas.  Feed them *plus* new variants to
    #    the referee so it can decide whether to keep using one of the former
    #    or switch to a fresh schema.
    # -------------------------------------------------------------------
    stored_schemas = [r.schema for r in existing_records]

    # We ask Variant-Generator for *at most* one balanced proposal so the
    # referee has a challenger if the stored ones are stale.
    challenger_variants = schema_variants.generate_variants(doc, minimal_only=True)

    all_candidates = stored_schemas + challenger_variants

    winner_idx, _reason = schema_variants.referee(all_candidates, doc)

    winning_schema = all_candidates[winner_idx]

    # If the winner is brand-new (i.e. came from challenger list) we persist it
    is_new = winner_idx >= len(stored_schemas)
    if is_new:
        schema_id = f"schema_{len(existing_records) + 1}"
        memory.save_schema_record(schema_id, winning_schema, rationale="promoted by referee")

    return winning_schema